apiVersion: v1
kind: Service
metadata:
  name: affiliate-bounty-board-backend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: affiliate-bounty-board-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: affiliate-bounty-board-backend
  name: affiliate-bounty-board-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: affiliate-bounty-board-backend
  template:
    metadata:
      labels:
        app: affiliate-bounty-board-backend
    spec:
      containers:
      - image: "{{DOCKER_REPO}}:{{GIT_COMMIT_SHA}}"
        imagePullPolicy: Always
        name: affiliate-bounty-board-backend
        envFrom:
        - secretRef:
            name: abb-secret-server-envs
        command: ["/abb"]
        args:
        - run
        - http-server
        - --temporal-address
        - $(TEMPORAL_ADDRESS)
        - --temporal-namespace
        - $(TEMPORAL_NAMESPACE)
        resources:
          requests:
            cpu: "200m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        readinessProbe:
          httpGet:
            path: /ping
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /ping
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
      restartPolicy: Always
      imagePullSecrets:
      - name: regcred