apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: affiliate-bounty-board
    component: workers
  name: affiliate-bounty-board-workers
spec:
  replicas: 2
  selector:
    matchLabels:
      app: affiliate-bounty-board
      component: workers
  template:
    metadata:
      labels:
        app: affiliate-bounty-board
        component: workers
    spec:
      containers:
      - image: "{{DOCKER_REPO}}:{{GIT_COMMIT_SHA}}"
        imagePullPolicy: Always
        name: affiliate-bounty-board-worker
        envFrom:
        - secretRef:
            name: affiliate-bounty-board-secret-worker-envs
        command: ["/abb"]
        args:
        - run
        - worker
        - --temporal-address
        - $(TEMPORAL_ADDRESS)
        - --temporal-namespace
        - $(TEMPORAL_NAMESPACE)
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        readinessProbe:
          exec:
            command:
            - /abb
            - run
            - worker
            - --check-connection
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          exec:
            command:
            - /abb
            - run
            - worker
            - --check-connection
          initialDelaySeconds: 15
          periodSeconds: 20
          timeoutSeconds: 5
      restartPolicy: Always
      imagePullSecrets:
      - name: regcred